name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true #Continue on error over a job in matrix tells to execute even if one of the job fails in matrix
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: [ubuntu-latest,windows-latest]
        include: #Will only runs with this combinations
          - node-version : 18
            operating-system: ubuntu-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build